name: cd-sudoku-musique
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cd-sudoku-musique.yaml
      - apps/generateur-musique/**
      - apps/generateur-sudoku/**
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
jobs:
  deploy-sudoku-musique:
    environment: Production â€“ generateur-musique-app-sudoku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 10.10.0
      - name: Use Node.js 20
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install turbo CLI
        run: pnpm install --global turbo

      - run: pnpm install --ignore-scripts

      - run: turbo build --filter=generateur-musique --filter=generateur-sudoku
      - name: Deploy Sudoku to Netlify
        uses: nwtgck/actions-netlify@4cbaf4c08f1a7bfa537d6113472ef4424e4eb654 # v3.0
        with:
          publish-dir: './apps/generateur-sudoku/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_GENERATEUR_SUDOKU_SITE_ID }}
        timeout-minutes: 1
      - name: Deploy Generateur Musique to Netlify
        uses: nwtgck/actions-netlify@4cbaf4c08f1a7bfa537d6113472ef4424e4eb654 # v3.0
        with:
          publish-dir: './apps/generateur-musique/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_GENERATEUR_MUSIQUE_SITE_ID }}
        timeout-minutes: 1
