name: e2e
on:
  push:
    paths:
      [
        'apps/bons-comptes-bons-amis/**',
        'apps/clavier-turbo-rapide/**',
        'apps/nirina-site/**',
      ]
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
permissions:
  contents: read # for checkout
jobs:
  ci:
    runs-on: ubuntu-22.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v4
        with:
          version: 9.14.2
      - name: Use Node.js 20
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Cache turbo build setup
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Install turbo
        run: pnpm i -g turbo

      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: '3.12'

      - name: Install python
        run: pip install -r requirements.txt
        working-directory: apps/bons-comptes-bons-amis

      - name: Install playwright browsers
        run: |
          pnpm exec playwright install
          pnpm exec playwright install-deps
      - run: turbo test:e2e --concurrency=1 --filter=\!nirina-site
  e2e-nirina-site:
    runs-on: ubuntu-22.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v4
        with:
          version: 9.14.2
      - name: Use Node.js 20
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Cache turbo build setup
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - run: turbo build --filter=nirina-site
      - name: Deploy to Netlify
        id: deploy-to-netlify
        uses: nwtgck/actions-netlify@4cbaf4c08f1a7bfa537d6113472ef4424e4eb654 # v3.0
        with:
          publish-dir: './apps/nirina-site/dist'
          netlify-config-path: './apps/nirina-site/netlify.toml'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_BLOG_SITE_ID }}
        timeout-minutes: 1
      - run: echo "PLAYWRIGHT_URL=$(echo ${{ steps.deploy-to-netlify.outputs.deploy-url }})" >> $GITHUB_ENV
      - run: turbo test:e2e --filter=nirina-site
